### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Ingvarr71** [Project-Fluid/manifest#11]
Hello! When assembling the firmware for Xiaomi Redmi Note 6 Pro, I get this error. How do I fix it?

[ 99% 556/557] finishing build rules ...
FAILED: 
hardware/qcom-caf/msm8998/audio/hal/Android.mk: error: "audio.primary.sdm660 (SHARED_LIBRARIES android-arm64) missing android.hardware.power-ndk_platform (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
hardware/qcom-caf/msm8998/audio/hal/Android.mk: error: "audio.primary.sdm660 (SHARED_LIBRARIES android-arm) missing android.hardware.power-ndk_platform (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:1125: error: exiting from previous errors.
09:09:34 ckati failed with: exit status 1

**Comment by azoller1** [comment]
Look here https://github.com/AOSPK/hardware_qcom_audio/commit/ce43467c56886e3b82b75cab54c422a168d9dc0e

**Comment by Ingvarr71** [comment]
> Look here [AOSPK/hardware_qcom_audio@ce43467](https://github.com/AOSPK/hardware_qcom_audio/commit/ce43467c56886e3b82b75cab54c422a168d9dc0e)

did not help

**Comment by ender1324** [comment]
you have to clone your own hals
